### ISSUE TITLE
Emails seems to be broken...

### ISSUE THREAD

**Issue by EarsKilla** [EarsKilla/Steam-Account-Generator#1]
Hi @Ashesh3, if i understand correctly, `newdedsecmail.now.sh` is your service.
So if it is, can you check what's wrong with it? And even if you won't to fix it, please reply here anyway.

Sample:
![screenshot](https://vgy.me/7nkSEx.png)

**Comment by Ashesh3** [comment]
Yes, but what exactly is wrong with it? Steam banned the email?

**Comment by EarsKilla** [comment]
If you are implemented some checker for mail provider bans on server... So maybe something is working wrong... Idk.
It seems that accounts was registered with these mail is working fine, but i cannot make new one.

For example:
`https://newdedsecmail.now.sh?alias=TediousEmbarrassedFunctionalBison`
responds with: `ok`, but expected mail provider (smth like `@newemail.mooo.com`)

It's works same with fully random aliases. Example: `swzvwlZWbfPU`

Or may be i'ts only for me?

**Comment by Ashesh3** [comment]
> If you are implemented some checker for mail provider bans on server... So maybe something is working wrong... Idk.
> It seems that accounts was registered with these mail is working fine, but i cannot make new one.
> 
> For example:
> `https://newdedsecmail.now.sh?alias=TediousEmbarrassedFunctionalBison`
> responds with: `ok`, but expected mail provider (smth like `@newemail.mooo.com`)
> 
> It's works same with fully random aliases. Example: `swzvwlZWbfPU`
> 
> Or may be i'ts only for me?

1st request: https://newdedsecmail.now.sh
Response : @domain.com

2nd request: https://newdedsecmail.now.sh/?alias=anything_u_want
response: ok

3rd request: https://newdedsecmail.now.sh/?alias=anything_u_want@domain.com
response: Steam Email

**Comment by EarsKilla** [comment]
Are you sure, that in 3rd request parameter name is `alias`? It's responds me `ok` always.
When i trying to use `e` as parameter, it's going to responds with `502 bad gateway` (lol).

Ofc, i proceed requests with info that you give me. 1st, 2nd and 3rd requests...

![screenshot](https://vgy.me/BNFZe0.png)

## 3rd request
new: `https://newdedsecmail.now.sh/?alias=crookedhistoricalstiffgrasshopper%40keepyourshitprivate.com`
- `ok`

old: `https://newdedsecmail.now.sh/?e=privatealikewetdeer%40keepyourshitprivate.com`
- `{"error": {"code": "502", "message": "An error occurred with your deployment"}}` (it's also bad gateway)
---
Sometimes server responds with `502 bad gateway` on 2nd request 🤔

I'm missing something?

**Comment by Ashesh3** [comment]
@EarsKilla

Suppose you want to access email for 
"cats@keepyourshitprivate.com"

Now you do do the following requests in order:

Get the domain
1. https://fapi.cloudaccess.host/mail.php
Response: @keepyourshitprivate.com


Now go to step 2
(Need to do this step 2 BEFORE u send this email to steam)
2. https://fapi.cloudaccess.host/mail.php?alias=cats
Response: ok


Now register with that email
Wait 5 seconds


(Actually getting steam email now)
3. https://fapi.cloudaccess.host/mail.php?e=catanddog@keepyourshitprivate.com
Response: steam email






P.s: I've updated the domain since the previous one(mentioned by you) caused 502 errors for no reason

**Comment by Ashesh3** [comment]
Also this step which you did was wrong
"https://newdedsecmail.now.sh/?alias=crookedhistoricalstiffgrasshopper%40keepyourshitprivate.com"

That is wrong

On ?alias you only specify name and NOT the domain
So it should have been

https://newdedsecmail.now.sh/?alias=crookedhistoricalstiffgrasshopper




P.s: as I said use the new domain now

**Comment by EarsKilla** [comment]
Yay! It's working now...

**Comment by Ashesh3** [comment]
Great!
