### ISSUE TITLE
[Question] Email access

### ISSUE THREAD

**Issue by Shaxzy** [EarsKilla/Steam-Account-Generator#11]
Hello
Any way to read the emails? at newemailsrv it only says @keepyourshitprivate.com

**Comment by EarsKilla** [comment]
I'm contracted with @Ashesh3 and receive answer that what are you want, unfortunately isn't possible.
So I can't help you with that (one of the reasons: I don't have any access to source code of this mail service).

I have only in my "to do" list implement modules support and here anyone can modify logic of mail service (captcha too) without any forks, but it will be in future. At this moment, I haven't too much time for some projects (including this), so I can't tell any dates when it will be done.
