### ISSUE TITLE
captcha not working

### ISSUE THREAD

**Issue by cancelpwnz** [EarsKilla/Steam-Account-Generator#19]
infinity loop with getting captcha, worked yesterday

**Comment by jponkenan** [comment]
does not work now

**Comment by jere021099** [comment]
Same here, also the email default domain doesn't work anymore, anyone has a working one or know a way to get one? Thx

**Comment by HSWG94** [comment]
suddenly it doesn't work, even when i tried with gmail. However, it works when i use the browser to manually create so its definitely not IP or gmail..

**Comment by EarsKilla** [comment]
@jere021099 valve was banned all free domains, so it's ok.

*2all* checking this issue...
