### ISSUE TITLE
Wrong Password failure

### ISSUE THREAD

**Issue by CripTonics** [EarsKilla/Steam-Account-Generator#2]
![error](https://user-images.githubusercontent.com/48637819/54487602-0e69d300-48a9-11e9-9e2f-0c6f9746f59b.png)
I received a password error
Thanks

**Comment by EarsKilla** [comment]
It's problem of `Neat password` function. They are adding `\r\n` to password...
Solution: Disable it while generating accounts and wait for fix

**Comment by CripTonics** [comment]
i did. Fixed 
What is the solution to this?"steam has disallowed your ip making this account"

**Comment by EarsKilla** [comment]
- Change IP address (it working only if your ISP providing dynamically addresses):
- - Disable internet connection, wait ~5-10 seconds, connect.
Most ISP will give another IP from their pool.
- - Reboot your router.
- Try to use proxy

Changing IP address help me always.

**Comment by CripTonics** [comment]
Can you add different games as a game? instead of CSgo

**Comment by EarsKilla** [comment]
It's possible, but i need to know their sub ID's.
For example ID for CS:GO is using sub ID `303386`

Or maybe just add field with custom sub ID 🤔

**Comment by EarsKilla** [comment]
Ok. I was found how to find it.
1. Take ID from store page.
2. Go to https://steamdb.info/
3. Write ID of game to search field and press Enter
4. Navigate to `Packages`, find in `BILLING TYPE` column `Free on Demand` and you will see sub id that we need

### Example
(Auf Abwegen)[https://store.steampowered.com/app/1036850/]

- ID `1036850`
- https://steamdb.info/app/1036850/subs/
- Sub ID `345249`

![chrome_2019-03-17_16-09-42](https://user-images.githubusercontent.com/17800772/54491376-2eac8880-48cf-11e9-8083-63b18a88a24f.png)

**Comment by CripTonics** [comment]
App ID:389430
Sub ID:73869

**Comment by Ashesh3** [comment]
> It's problem of `Neat password` function. They are adding `\r\n` to password...
> Solution: Disable it while generating accounts and wait for fix

pretty sure u can strip them from the response from the password api

**Comment by EarsKilla** [comment]
Yeah, fix is easy. just call method `.Trim()` and all seems to be ok...
