### ISSUE TITLE
Program doesn't work

### ISSUE THREAD

**Issue by caiovrcombat** [EarsKilla/Steam-Account-Generator#21]
When I try to create an account, the program gets stuck in the captcha and does not generate anything.

**Comment by despa1r1337** [comment]
you are using the old version, upgrade. 
https://github.com/EarsKilla/Steam-Account-Generator/releases/tag/v1.1.3.3

**Comment by despa1r1337** [comment]
> When I try to create an account, the program gets stuck in the captcha and does not generate anything.

you are using the old version, update.
https://github.com/EarsKilla/Steam-Account-Generator/releases/tag/v1.1.3.3

**Comment by EarsKilla** [comment]
solved? if no any reply closing in 3 days

**Comment by caiovrcombat** [comment]
Solved! Thansk :D  but i have another question

How can I change my email address? Steam does not allow the address keypad.com

http://prntscr.com/o3lg3w

**Comment by SmokyTheGun** [comment]
yep that info would be nice. or i have just to creato email adresses by myself?

**Comment by MrLolik** [comment]
Doesn't work again! Parameter "sitekey" deleted.

**Comment by despa1r1337** [comment]
> Solved! Thansk :D but i have another question
> 
> How can I change my email address? Steam does not allow the address keypad.com
> 
> http://prntscr.com/o3lg3w

Valve banned all domains that were free, you can buy a domain here: https://www.reg.ru/ and use it by setting the domain according to: https://github.com/EarsKilla/Steam-Account-Generator/ wiki / using-custom-mail-domain
