### ISSUE TITLE
Load proxy list from file

### ISSUE THREAD

**Issue by ItsOnlyMeNL** [EarsKilla/Steam-Account-Generator#22]
Hi,

I was wondering in what format i need to create the .txt file for loading the proxy's in.  I have been trying to load it in from file but i am unable to import a proxy list. 

Could you please show a example on how the file must look so i can add my proxy's? 

Regards,

**Comment by despa1r1337** [comment]
> Привет,
> 
> Мне было интересно, в каком формате мне нужно создать файл .txt для загрузки прокси-сервера. Я пытался загрузить его из файла, но не могу импортировать список прокси.
> 
> Не могли бы вы показать пример того, как должен выглядеть файл, чтобы я мог добавить свои прокси?
> 
> С Уважением,

![Снимаакаок](https://user-images.githubusercontent.com/48297813/59879492-80275080-93b3-11e9-8ce2-02c0c992e832.PNG)

**Comment by despa1r1337** [comment]
> Привет,
> 
> Мне было интересно, в каком формате мне нужно создать файл .txt для загрузки прокси-сервера. Я пытался загрузить его из файла, но не могу импортировать список прокси.
> 
> Не могли бы вы показать пример того, как должен выглядеть файл, чтобы я мог добавить свои прокси?
> 
> С Уважением,

![загрузка прокси](https://user-images.githubusercontent.com/48297813/59879920-7ce09480-93b4-11e9-82f2-f1068606fc39.PNG)
![открыть](https://user-images.githubusercontent.com/48297813/59879921-7ce09480-93b4-11e9-9241-7ab0f7437999.PNG)
![галочки](https://user-images.githubusercontent.com/48297813/59879922-7ce09480-93b4-11e9-9359-0120da3c7dfd.PNG)

**Comment by despa1r1337** [comment]
> Привет,
> 
> Мне было интересно, в каком формате мне нужно создать файл .txt для загрузки прокси-сервера. Я пытался загрузить его из файла, но не могу импортировать список прокси.
> 
> Не могли бы вы показать пример того, как должен выглядеть файл, чтобы я мог добавить свои прокси?
> 
> С Уважением,

![прокси лист](https://user-images.githubusercontent.com/48297813/59880055-c8933e00-93b4-11e9-9aad-1bf62bc1368a.PNG)

**Comment by ItsOnlyMeNL** [comment]
Thanks, this works!

**Comment by despa1r1337** [comment]
Thanks for contactin.
