### ISSUE TITLE
What should be used proxy for the generator? and is it possible to use mail yandex.ru?

### ISSUE THREAD

**Issue by JustKeruk** [EarsKilla/Steam-Account-Generator#24]
Sorry for my english (google translate)
And if you use a proxy from this site, then all the bad
[https://awmproxy.com/freeproxy.php?g-recaptcha-response=03AOLTBLSjeDkwHlkQvhvU7Bmn1rIeImnS5Wucjg_akOFOjPNq0Pp-8ezt5GQVEhgBq1dlkNVPMGgo-Src6qi1zRh-Nn91PRlctX1yJPb5ZbBwDqZfpEiMKmSdnyYD1EzVzVm5TtSxnD2VXD3AcM40VrywUePt7obSQ3ZcLrNM41F4QMAx_f4BKpS40n_x_Llb8OEUl0z9YmToYHSqrq0SsI4FwpWdN7GHrfT0Ss_asc2T0BsRnayRCo_7TyaqHWd-nOu8mPfP13dnw-ZzrH6I825th27YtG3aUk8eqZfyrSO1SGBRGRUBqns6rTH2TwUQV-AR3W2sUuIC&op=getlink](url)

**Comment by JustKeruk** [comment]
And if you use a proxy from this site, then all the bad[https://awmproxy.com/freeproxy.php?g-recaptcha-response=03AOLTBLSjeDkwHlkQvhvU7Bmn1rIeImnS5Wucjg_akOFOjPNq0Pp-8ezt5GQVEhgBq1dlkNVPMGgo-Src6qi1zRh-Nn91PRlctX1yJPb5ZbBwDqZfpEiMKmSdnyYD1EzVzVm5TtSxnD2VXD3AcM40VrywUePt7obSQ3ZcLrNM41F4QMAx_f4BKpS40n_x_Llb8OEUl0z9YmToYHSqrq0SsI4FwpWdN7GHrfT0Ss_asc2T0BsRnayRCo_7TyaqHWd-nOu8mPfP13dnw-ZzrH6I825th27YtG3aUk8eqZfyrSO1SGBRGRUBqns6rTH2TwUQV-AR3W2sUuIC&op=getlink](url)

**Comment by EarsKilla** [comment]
Proxy file formatted like [here](https://github.com/EarsKilla/Steam-Account-Generator/wiki/Proxy-file-format%3F)?

**Comment by JustKeruk** [comment]
No,you misunderstood me. I need proxies that work with this generator. Not that as they have to be in the file, and proxies. I can recommend the website with the workers in the proxy generator.

**Comment by despa1r1337** [comment]
> Нет, вы меня неправильно поняли. Мне нужны прокси, которые работают с этим генератором. Не то что они должны быть в файле, а прокси. Я могу порекомендовать сайт с работниками в прокси-генераторе.

1) free proxies
https://top-proxies.ru/free_proxy.php
https://hidemyna.me/ru/proxy-list

2) how to load a proxy in the program
https://github.com/EarsKilla/Steam-Account-Generator/issues/22

**Comment by despa1r1337** [comment]
1) What should be used proxy for the generator? 
 
After creating 11 accounts, your IP is blocked by Steam for 24 hours. To do this, you need a proxy to bypass the block and create more accounts.

2) and is it possible to use mail yandex.ru? 

I don't know about the use of yandex.ru mail, you can ask EarsKilla, but I found how to use gmail mail. You can easy  create gmail mail and use it according to this instruction https://github.com/EarsKilla/Steam-Account-Generator/wiki/Using-gmail

**Comment by EarsKilla** [comment]
I'm not tried yet with yandex, but it will work cuz we just forwarding mails from steam to another inbox. So i think you need to configure it like for [google](https://github.com/EarsKilla/Steam-Account-Generator/wiki/Using-gmail)

---

Also dev versions supports custom mail handler. You can look at [sample of mail handler](https://github.com/EarsKilla/Steam-Account-Generator/blob/dev/SampleModule/MailBox.cs).  
If one mail box for all accounts is enough for you, you can compile sample module (just download all project data from `dev` branch and compile all using VS2017) and configure IMAP settings (you can follow [this](https://yandex.com/support/mail/mail-clients.html) help page)

---

ps, valve was banned `@yandex.com`  

![lmao](https://i.vgy.me/vIG5xx.png)

**Comment by despa1r1337** [comment]
you can also buy a domain here: https://www.reg.ru/ and use  it by setting the domain according to:https://github.com/EarsKilla/Steam-Account-Generator/wiki/using-custom-mail-domain 

It all depends on you, which method is more convenient, then use it. If we have answered your question and you have resolved the problem, you can close the issue. If you encounter problems, do not hesitate to contact us.

**Comment by JustKeruk** [comment]
In the generator in the line mail - you will need to write mailhost.root.sx or my Gmail?

**Comment by despa1r1337** [comment]
> In the generator in the line mail - you will need to write mailhost.root.sx or my Gmail?


your

**Comment by JustKeruk** [comment]
Thank you all for everything)

**Comment by despa1r1337** [comment]
> Thank you all for everything)


did you succeed?

**Comment by JustKeruk** [comment]
Not check. But you all have so painted that I think it will work <3

**Comment by despa1r1337** [comment]
> Not check. But you all have so painted that I think it will work <3


if you have problems, please contact

**Comment by JustKeruk** [comment]
Necessarily. With this support, the problems can be solved and solved :D
