### ISSUE TITLE
What is wrong ?

### ISSUE THREAD

**Issue by sterlicya** [EarsKilla/Steam-Account-Generator#26]
![why i cant](https://user-images.githubusercontent.com/25007736/60801247-5aee5c80-a17f-11e9-9a22-d3cee6cdd2a3.PNG)

**Comment by Ashesh3** [comment]
Should be fixed now. Server had some logic issues.

**Comment by EarsKilla** [comment]
close issue?

**Comment by Ashesh3** [comment]
Yes. Can be closed.
