### ISSUE TITLE
auto captcha not working 

### ISSUE THREAD

**Issue by tolunayilhan** [EarsKilla/Steam-Account-Generator#3]
using 2CAPTCHA but not working.

wants to enter captcha.
 
![capccc](https://user-images.githubusercontent.com/44772672/54596943-52daa780-4a3e-11e9-8d6e-74948f10aff6.jpg)

**Comment by EarsKilla** [comment]
probably fixed 2captcha/rucaptcha... wait for commits and build.
for now making a final touch...
